import dummyImage from "../assets/dummy.jpg";
import { DataBarangType } from "@/types/global";

export const DataBarang: DataBarangType[] = [
	{
		id: 1,
		gambar: dummyImage,
		nama: "Proyektor",
		desc: "Proyektor berkualitas tinggi untuk presentasi dan menonton film.",
		stok: 24,
		kategori: "Elektronik",
	},
	{
		id: 2,
		gambar: dummyImage,
		nama: "Speaker",
		desc: "Speaker portabel dengan suara jernih dan bass mantap.",
		stok: 12,
		kategori: "Audio",
	},
	{
		id: 3,
		gambar: dummyImage,
		nama: "Laptop",
		desc: "Laptop performa tinggi untuk kerja dan gaming ringan.",
		stok: 15,
		kategori: "Komputer",
	},
	{
		id: 4,
		gambar: dummyImage,
		nama: "Mikrofon",
		desc: "Mikrofon kondensor dengan kualitas audio profesional.",
		stok: 30,
		kategori: "Audio",
	},
	{
		id: 5,
		gambar: dummyImage,
		nama: "Kamera DSLR",
		desc: "Kamera DSLR dengan lensa kit untuk fotografi dan video.",
		stok: 8,
		kategori: "Fotografi",
	},
	{
		id: 6,
		gambar: dummyImage,
		nama: "Tripod",
		desc: "Tripod aluminium ringan untuk kamera dan smartphone.",
		stok: 18,
		kategori: "Aksesoris",
	},
	{
		id: 7,
		gambar: dummyImage,
		nama: "Monitor LED",
		desc: "Monitor Full HD dengan warna tajam dan refresh rate tinggi.",
		stok: 10,
		kategori: "Komputer",
	},
	{
		id: 8,
		gambar: dummyImage,
		nama: "Printer",
		desc: "Printer multifungsi untuk cetak, scan, dan fotokopi.",
		stok: 6,
		kategori: "Peralatan Kantor",
	},
	{
		id: 9,
		gambar: dummyImage,
		nama: "Scanner",
		desc: "Scanner dokumen resolusi tinggi untuk kebutuhan kantor.",
		stok: 5,
		kategori: "Peralatan Kantor",
	},
	{
		id: 10,
		gambar: dummyImage,
		nama: "Whiteboard",
		desc: "Whiteboard magnetik untuk presentasi dan brainstorming.",
		stok: 7,
		kategori: "Peralatan Kantor",
	},
	{
		id: 11,
		gambar: dummyImage,
		nama: "Monitor AMOLED",
		desc: "Monitor 4k dengan warna tajam dan refresh rate tinggi.",
		stok: 10,
		kategori: "Komputer",
	},
	{
		id: 12,
		gambar: dummyImage,
		nama: "Kamera Mirrorless",
		desc: "ya begitulah",
		stok: 15,
		kategori: "Fotografi",
	},
	{
		id: 13,
		gambar: dummyImage,
		nama: "blackboard",
		desc: "blackboard magnetik untuk presentasi dan brainstorming.",
		stok: 7,
		kategori: "Peralatan Kantor",
	},
];
