import dummyImage from "../assets/dummy.jpg";
import { DataBarangType } from "@/types/global";

export const DataBarang: DataBarangType[] = [
	{
		id: 1,
		gambar: dummyImage,
		nama: "Proyektor LCD",
		desc: "Proyektor LCD dengan resolusi HD 1080p, brightness 3000 lumens, cocok untuk presentasi dan home theater. Mendukung koneksi HDMI dan USB.",
		stok: 24,
		kategori: "Elektronik",
	},
	{
		id: 2,
		gambar: dummyImage,
		nama: "Speaker Bluetooth",
		desc: "Speaker portabel dengan teknologi Bluetooth 5.0, suara jernih dan bass mantap. Daya tahan baterai hingga 12 jam.",
		stok: 12,
		kategori: "Audio",
	},
	{
		id: 3,
		gambar: dummyImage,
		nama: "Laptop Gaming",
		desc: "Laptop gaming dengan processor Intel i7, GPU RTX 3060, RAM 16GB, dan SSD 512GB. Cocok untuk kerja dan gaming.",
		stok: 15,
		kategori: "Komputer",
	},
	{
		id: 4,
		gambar: dummyImage,
		nama: "Mikrofon Kondensor",
		desc: "Mikrofon kondensor USB dengan kualitas audio profesional untuk recording dan streaming. Includes shock mount dan pop filter.",
		stok: 30,
		kategori: "Audio",
	},
	{
		id: 5,
		gambar: dummyImage,
		nama: "Kamera DSLR",
		desc: "Kamera DSLR 24.2MP dengan lensa kit 18-55mm, cocok untuk fotografi dan videografi pemula hingga menengah.",
		stok: 8,
		kategori: "Fotografi",
	},
	{
		id: 6,
		gambar: dummyImage,
		nama: "Tripod Kamera",
		desc: "Tripod aluminium ringan dengan tinggi adjustable hingga 160cm. Cocok untuk kamera DSLR dan smartphone.",
		stok: 18,
		kategori: "Aksesoris Fotografi",
	},
	{
		id: 7,
		gambar: dummyImage,
		nama: 'Monitor Gaming 27"',
		desc: 'Monitor LED 27" Full HD dengan refresh rate 144Hz, response time 1ms, dan teknologi FreeSync untuk pengalaman gaming yang smooth.',
		stok: 10,
		kategori: "Komputer",
	},
	{
		id: 8,
		gambar: dummyImage,
		nama: "Printer Multifungsi",
		desc: "Printer all-in-one untuk cetak, scan, dan fotokopi dengan konektivitas WiFi dan USB. Kecepatan cetak hingga 15 ppm.",
		stok: 6,
		kategori: "Peralatan Kantor",
	},
	{
		id: 9,
		gambar: dummyImage,
		nama: "Scanner Dokumen",
		desc: "Scanner flatbed dengan resolusi optik 4800 dpi untuk digitalisasi dokumen beresolusi tinggi. Mendukung format PDF dan JPEG.",
		stok: 5,
		kategori: "Peralatan Kantor",
	},
	{
		id: 10,
		gambar: dummyImage,
		nama: "Whiteboard Magnetik",
		desc: "Whiteboard magnetik 120x90cm dengan permukaan halus untuk presentasi dan brainstorming. Dilengkapi dengan marker dan penghapus.",
		stok: 7,
		kategori: "Peralatan Kantor",
	},
	{
		id: 11,
		gambar: dummyImage,
		nama: "Monitor 4K AMOLED",
		desc: 'Monitor 32" 4K UHD dengan panel AMOLED, warna tajam, dan HDR support. Cocok untuk desain grafis dan video editing.',
		stok: 10,
		kategori: "Komputer",
	},
	{
		id: 12,
		gambar: dummyImage,
		nama: "Kamera Mirrorless",
		desc: "Kamera mirrorless 20.1MP dengan sensor APS-C, autofocus cepat, dan perekaman video 4K. Cocok untuk traveling dan fotografi profesional. :cite[9]",
		stok: 15,
		kategori: "Fotografi",
	},
	{
		id: 13,
		gambar: dummyImage,
		nama: "Blackboard",
		desc: "Papan tulis tradisional dengan permukaan yang dapat ditulis menggunakan kapur. Ukuran 100x150cm, dilengkapi dengan bingkai kayu. :cite[4]",
		stok: 7,
		kategori: "Peralatan Pendidikan",
	},
	{
		id: 14,
		gambar: dummyImage,
		nama: "Kabel HDMI Premium",
		desc: "Kabel HDMI 2.0 high-speed dengan bandwidth 18Gbps, mendukung 4K@60Hz dan HDR. Panjang 2 meter.",
		stok: 50,
		kategori: "Elektronik",
	},
	{
		id: 15,
		gambar: dummyImage,
		nama: "Mouse Wireless",
		desc: "Mouse ergonomis dengan konektivitas wireless 2.4GHz dan Bluetooth. Baterai tahan hingga 6 bulan dengan sensor optik presisi.",
		stok: 25,
		kategori: "Komputer",
	},
	{
		id: 16,
		gambar: dummyImage,
		nama: "Keyboard Mechanical",
		desc: "Keyboard mechanical dengan switch Blue, backlit RGB, dan layout 87 key. Material ABS double-shot keycaps.",
		stok: 18,
		kategori: "Komputer",
	},
	{
		id: 17,
		gambar: dummyImage,
		nama: "Headphone Noise-Cancelling",
		desc: "Headphone over-ear dengan active noise cancellation, battery life 30 jam, dan konektivitas Bluetooth 5.0.",
		stok: 14,
		kategori: "Audio",
	},
	{
		id: 18,
		gambar: dummyImage,
		nama: "Tablet Graphic Drawing",
		desc: "Tablet graphic 10x6 inch dengan 4096 pressure levels, compatible dengan Photoshop dan Illustrator. Cocok untuk digital art.",
		stok: 9,
		kategori: "Desain Grafis",
	},
	{
		id: 19,
		gambar: dummyImage,
		nama: "Smartphone Flagship",
		desc: "Smartphone flagship dengan processor Snapdragon 8 Gen 2, kamera 108MP, layar AMOLED 120Hz, dan baterai 5000mAh.",
		stok: 22,
		kategori: "Elektronik",
	},
	{
		id: 20,
		gambar: dummyImage,
		nama: "Webcam 4K",
		desc: "Webcam 4K dengan autofocus, microphone array noise-cancelling, dan low-light correction. Cocok untuk streaming dan conference.",
		stok: 17,
		kategori: "Komputer",
	},
];
