import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import SessionClient from '@/components/SessionClient';
import { Toaster } from '@/components/ui/sonner';
import { CacheProviders } from './cacheProviders';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'borrowfy App - Peminjaman Gudang Mudah',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CacheProviders>
          <SessionClient>{children}</SessionClient>
          <Toaster />
        </CacheProviders>
      </body>
    </html>
  );
}
